// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6q0LT1BZ4h8V-ChIL9nx_xTzlmQWF6y4',
    appId: '1:1020539909116:web:abdc2dd3d2bf4e936b3879',
    messagingSenderId: '1020539909116',
    projectId: 'think-task',
    authDomain: 'think-task.firebaseapp.com',
    storageBucket: 'think-task.appspot.com',
    measurementId: 'G-DM8KRYXDFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJkYdAf6KdBoCnjQVIaS1pdkZTPlIm8k',
    appId: '1:1020539909116:android:0717b1a45881e9e96b3879',
    messagingSenderId: '1020539909116',
    projectId: 'think-task',
    storageBucket: 'think-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBCjgSRRUnIIOaYOFiNqUFzwR35mYX2nE',
    appId: '1:1020539909116:ios:65026cef5f4aa8bb6b3879',
    messagingSenderId: '1020539909116',
    projectId: 'think-task',
    storageBucket: 'think-task.appspot.com',
    iosBundleId: 'com.example.thinkTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBCjgSRRUnIIOaYOFiNqUFzwR35mYX2nE',
    appId: '1:1020539909116:ios:548b8a3e1dda93ed6b3879',
    messagingSenderId: '1020539909116',
    projectId: 'think-task',
    storageBucket: 'think-task.appspot.com',
    iosBundleId: 'com.example.thinkTask.RunnerTests',
  );
}
